name: Codecov

on:
  # Run on master changes to track test coverage over time
  push:
    branches:
      - 'master'
  # Leave a PR comment to surface test coverage changes
  pull_request: ~

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install deps
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
