name: ci

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: npm ci

      - name: Validate
        run: npm run validate

      # This action will usually create (or update) a "release" PR, containing a version bump and changelog updates
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      # If the above action creates a GitHub release, then also publish to npm
      # This must be attached to this workflow, as one workflow cannot trigger another (e.g. on release create)
      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
