name: Branch workflow

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run validate
